// The controls, in the simulator: keys, the pointer, the formula box, the read-out.
//   node test/ui.mjs
import { createSim } from '../sim.mjs';
let bad = 0;
const ok = (c, what, ...more) => { if (!c) { bad++; console.log('FAIL', what, ...more); } };
const s = createSim();
const run = (n) => { for (let i = 0; i < n; i++) s.frame(); };
const press = (code, n = 3) => { s.keys.add(code); run(n); s.keys.delete(code); run(2); };
const enter = (text) => { s.answers.push(text); press(13); };
run(3);
ok(s.peek('helpOn') === 1 && s.base.help.visible, 'help shown at the start');
ok(s.text('top') === 'f(z) = (z^2-1)(z-2-i)^2/(z^2+2+2i)', 'first formula', s.text('top'));
press(50);
ok(s.peek('helpOn') === 0 && !s.base.help.visible, 'a key hides the help');
ok(s.text('top') === 'f(z) = z', 'key 2', s.text('top'));
s.settle();
// the read-out
s.mouse.x = 64; s.mouse.y = -32; run(2);
ok(s.text('bot') === 'z = 1 - 0.5i   f(z) = 1 - 0.5i   |f| = 1.118   arg = -27°   눈금 1', 'read-out', s.text('bot'));
// a formula typed in
enter('z^2');
ok(s.text('top') === 'f(z) = z^2', 'typed formula', s.text('top'));
run(2);
ok(s.text('bot').includes('f(z) = 0.75 - i   |f|'), 'read-out of z^2', s.text('bot'));
enter('2^^z');
ok(s.text('top').startsWith('식이 맞지 않습니다 (3번째 글자)'), 'error shown', s.text('top'));
ok(s.peek('fsrc') === 'z^2' && s.peek('cerr') === 0, 'the old formula stays');
run(260);
ok(s.text('top') === 'f(z) = z^2', 'error goes away', s.text('top'));
enter('');
ok(s.text('top') === 'f(z) = z^2', 'empty answer changes nothing');
enter('(1+2i)^(3-i)');
ok(s.text('top') === '(1+2i)^(3-i) = -27.43638199 + 19.78931037i', 'calculator', s.text('top'));
enter('e^(i pi)');
ok(s.text('top') === 'e^(i pi) = -1' || /^e\^\(i pi\) = -1 [+-] \d\.\d+e-1[67]i$/.test(s.text('top')), 'calculator: Euler', s.text('top'));
enter('1/3');
ok(s.text('top') === '1/3 = 0.3333333333', 'calculator: 1/3', s.text('top'));
enter('zeta(2)');
ok(s.text('top') === 'zeta(2) = 1.644934067', 'calculator: zeta(2)', s.text('top'));
enter('gamma(5)');
ok(s.text('top') === 'gamma(5) = 24', 'calculator: gamma(5)', s.text('top'));
enter('zeta(-1)');
ok(s.text('top') === 'zeta(-1) = -0.08333333333', 'calculator: zeta(-1)', s.text('top'));
enter('1/e^50');
ok(s.text('top') === '1/e^50 = 1.928749848e-22', 'calculator: a small quotient', s.text('top'));
enter('z^3-1');
// zoom keeps the point under the pointer
s.mouse.x = 100; s.mouse.y = 50; run(2);
const at = () => [s.peek('vcx') + s.mouse.x * s.peek('vupp'), s.peek('vcy') + s.mouse.y * s.peek('vupp')];
const p0 = at(); const u0 = s.peek('vupp');
press(90);
ok(s.peek('vupp') === u0 / 2, 'zoom in halves the scale', s.peek('vupp'));
ok(Math.abs(at()[0] - p0[0]) < 1e-12 && Math.abs(at()[1] - p0[1]) < 1e-12, 'zoom keeps the pointed point');
press(88); press(88);
ok(s.peek('vupp') === u0 * 2, 'zoom out');
press(82);
ok(s.peek('vcx') === 0 && s.peek('vcy') === 0 && s.peek('vupp') === 0.015625, 'R resets the view');
// dragging
s.mouse.x = 0; s.mouse.y = 0; run(2);
s.mouse.down = true; run(1);
for (let i = 1; i <= 10; i++) { s.mouse.x = 6 * i; s.mouse.y = 3 * i; run(1); }
s.mouse.down = false; run(1);
ok(Math.abs(s.peek('vcx') + 60 * 0.015625) < 1e-12 && Math.abs(s.peek('vcy') + 30 * 0.015625) < 1e-12, 'drag moves the view', s.peek('vcx'), s.peek('vcy'));
// arrows
const x1 = s.peek('vcx'); s.keys.add(39); run(5); s.keys.delete(39); run(1);
ok(Math.abs(s.peek('vcx') - x1 - 5 * 6 * 0.015625) < 1e-12, 'arrow key', s.peek('vcx') - x1);
// colour mode, axes
const m0 = s.peek('cmode'); press(67); ok(s.peek('cmode') === (m0 + 1) % 4, 'C changes the colour mode');
s.settle();
ok(s.base.axes.pen.strokes.length > 2, 'axes drawn', s.base.axes.pen.strokes.length);
press(65); run(2); ok(s.base.axes.pen.strokes.length === 0, 'A hides the axes');
press(65);
// a long drag on a slow machine: the clones must not pile up, and the picture must end right
s.poke('budget', 60); s.poke('paceKnown', 1); s.poke('fpsNow', 17); s.poke('bFail', 61);
s.mouse.x = -100; s.mouse.y = -50; run(1); s.mouse.down = true;
let maxAlive = 0;
const penClones = () => s.entities.filter(e => e.obj === 'pen' && e.clone && !e.dead).length;
for (let i = 0; i < 900; i++) { s.mouse.x = -100 + (i % 200); s.mouse.y = -50 + (i % 77); s.poke('budget', 60); run(1); maxAlive = Math.max(maxAlive, penClones()); }
s.mouse.down = false;
ok(maxAlive < 60, 'clones during a long drag', maxAlive);
s.poke('budget', 20000);
const n = s.settle();
ok(s.peek('rState') === 0 && s.peek('pcx') === s.peek('vcx') && s.peek('pupp') === s.peek('vupp'), 'picture of the last view', n);
ok(penClones() < 60, 'clones at rest', penClones());
// ---- v1.1: zeros and poles by a click, the parameters a and t
const click = (x, y) => { s.mouse.x = x; s.mouse.y = y; run(1); s.mouse.down = true; run(2); s.mouse.down = false; run(2); };
press(82);
enter('z^3-1');
click(67, 3);
ok(s.text('top') === '영점 z = 1', 'click finds the zero 1', s.text('top'));
click(-30, 58);
ok(s.text('top') === '영점 z = -0.5 + 0.8660254038i', 'click finds another zero', s.text('top'));
ok(s.peek('MKX').length === 2 && s.peek('MKK')[0] === 1, 'two markers', s.peek('MKX').length);
click(-30, 57);
ok(s.peek('MKX').length === 2, 'the same zero is marked once');
enter('(z^2-1)(z-2-i)^2/(z^2+2+2i)');
ok(s.peek('MKX').length === 0, 'a new formula clears the markers');
click(125, 60);
ok(s.text('top') === '영점 z = 2 + i  (2겹)', 'a double zero', s.text('top'));
click(-50, 100);
ok(s.text('top') === '극 z = -0.6435942529 + 1.553773974i', 'a pole', s.text('top'));
enter('e^z');
click(10, 10);
ok(s.text('top') === '가까운 영점이나 극을 찾지 못했습니다', 'nothing to find', s.text('top'));
run(400);
ok(s.text('top') === 'f(z) = e^z', 'the message goes away', s.text('top'));
enter('1/z^3');
click(4, -3);
ok(s.text('top') === '극 z = 0  (3겹)' || /^극 z = -?\d\.\d+e-\d+/.test(s.text('top')), 'a triple pole', s.text('top'));
// a: follows the pointer while S is held
enter('z^2+a');
ok(s.text('top') === 'f(z) = z^2+a   a = 1', 'a in the label', s.text('top'));
s.mouse.x = 32; s.mouse.y = -64; s.keys.add(83); run(2); s.keys.delete(83); run(1);
ok(s.peek('aRe') === 0.5 && s.peek('aIm') === -1 && s.text('top') === 'f(z) = z^2+a   a = 0.5 - i', 'S moves a', s.text('top'));
s.mouse.x = 0; s.mouse.y = 0; run(2);
ok(s.text('bot').startsWith('z = 0   f(z) = 0.5 - i'), 'the read-out uses a', s.text('bot'));
s.poke('budget', 20000); s.settle();
ok(s.peek('pAr') === 0.5 && s.peek('pAi') === -1, 'the picture is of that a');
// t: runs, stops with the space bar
enter('z^3+e^(it)');
const t0 = s.peek('tPar'); run(60);
ok(Math.abs(s.peek('tPar') - t0 - 1) < 0.02, 't runs with the clock', s.peek('tPar') - t0);
ok(/^f\(z\) = z\^3\+e\^\(it\)   t = [\d.]+ ▶$/.test(s.text('top')), 't in the label', s.text('top'));
ok(s.peek('rLevel') <= s.peek('baseLevel'), 'while t runs only the first pass is drawn', s.peek('rLevel'));
press(32);
const t1 = s.peek('tPar'); run(30);
ok(s.peek('tPar') === t1 && s.text('top').endsWith('■'), 'space stops t', s.text('top'));
s.settle();
ok(s.peek('rLevel') === s.peek('maxLevel') && s.peek('pT') === t1, 'stopped: the picture is finished at that t', s.peek('rLevel'));
press(32);
// the examples one after another: every one must compile
press(49);
for (let i = 2; i <= 26; i++) { press(190); ok(s.peek('cerr') === 0 && s.peek('exAt') === (i - 1) % 25 + 1, 'example ' + i, s.text('top')); if (i === 22) ok(s.peek('aRe') === -0.8 && s.peek('aIm') === 0.156 && s.peek('vcx') === 0, 'example 22 brings its a'); if (i === 21) ok(s.peek('vcx') === -0.6, 'example 21 brings its centre'); }
ok(s.text('top').startsWith('f(z) = (z^2-1)(z-2-i)^2'), 'the examples wrap around', s.text('top'));
press(188);
ok(s.peek('exAt') === 25, 'and back');
// ---- v1.2: the picture of a grid
press(51);
s.poke('budget', 20000); s.settle();
press(71); run(3);
ok(s.peek('gridOn') === 1 && s.text('top').endsWith('[격자]') && s.base.grid.pen.strokes.length > 500, 'G draws the grid picture', s.base.grid.pen.strokes.length);
ok(s.peek('gLine') === s.peek('gTotal') && s.peek('gTotal') === 31 + 17, 'all its lines', s.peek('gTotal'));
const g0 = s.base.grid.pen.strokes.length; s.keys.add(39); run(3); s.keys.delete(39); run(3);
ok(s.peek('gcx') === s.peek('vcx') && s.base.grid.pen.strokes.length !== g0, 'it follows the view');
enter('1/z'); run(3);
ok(s.peek('gLine') === s.peek('gTotal') && s.base.grid.pen.strokes.length > 300, 'a pole does not break it', s.base.grid.pen.strokes.length);
s.poke('budget', 96); press(82); run(1); const gl = s.peek('gLine'); run(5);
ok(gl < s.peek('gTotal') && s.peek('gLine') === gl + 5, 'a slow machine draws a line a frame', gl, s.peek('gLine'));
s.poke('budget', 20000); run(3);
press(71); run(2);
ok(s.peek('gridOn') === 0 && s.base.grid.pen.strokes.length === 0, 'G again takes it away');
press(82);
// ---- v2.0: the surface and the sphere
const fills = () => s.base.solid.pen.strokes.length;
press(51);
s.poke('budget', 30000);
press(86); run(4);
ok(s.peek('view3') === 1 && s.text('top').endsWith('[3D]') && fills() === 1 + 60 * 34, 'V: the surface, every cell filled', fills());
ok(s.peek('s3Have') === 1 && s.peek('s3Pass') === 0, 'both passes done');
const hv = s.peek('HV'), hk = s.peek('HK');
// the vertex at the zero z = 1 (column 38 of 61: x = (38/60 - 1/2) * 480 / 64 = 1, row 17) is at the bottom
ok(hv[17 * 61 + 38] === 0 && hk[17 * 61 + 38] === 72 * 10 + 20 + 1, 'the zero is at the bottom, and black', hv[17 * 61 + 38], hk[17 * 61 + 38]);
ok(hv[0] > 0.8 && hv[0] < 1, 'far from the zeros the surface is high', hv[0]);
const gen = s.peek('s3Gen');
s.mouse.x = 0; s.mouse.y = 0; run(1); s.mouse.down = true; run(1); s.mouse.x = 50; s.mouse.y = -20; run(2);
ok(s.peek('az') === 60 && s.peek('el') === 45 && s.peek('vcx') === 0, 'dragging turns it', s.peek('az'), s.peek('el'));
s.mouse.down = false; run(2);
ok(s.peek('s3Gen') === gen && s.peek('s3Az') === 60 && fills() === 2041, 'turning draws again without working f out again');
ok(s.peek('MKX').length === 0, 'a click finds nothing on a mesh');
// on a slow machine the coarse mesh while it is turned
s.poke('budget', 100); s.poke('bFail', 101);
s.mouse.down = true; run(1); s.mouse.x = 80; run(2);
ok(s.peek('s3St') === 2 && fills() === 1 + 30 * 17, 'a slow machine turns the coarse mesh', fills());
s.mouse.down = false; run(2);
ok(s.peek('s3St') === 1 && fills() === 2041, 'and draws the fine one when let go', fills());
s.poke('budget', 30000);
s.keys.add(39); run(2); s.keys.delete(39); run(4);
ok(s.peek('s3Gen') === s.peek('vgen') && s.peek('s3cx') === s.peek('vcx') && s.peek('s3Have') === 1, 'moving the view works the surface out anew');
press(82);
press(86); run(4);
ok(s.peek('view3') === 2 && s.text('top').endsWith('[구]') && fills() > 1200 && fills() < 1400, 'V again: the sphere, its near half', fills());
s.poke('az', 0); s.poke('el', 0); s.mouse.x = 0; s.mouse.y = 0; run(2);
ok(s.text('bot').startsWith('z = -i   f(z) = -1 + i'), 'the pointer on the sphere reads the plane', s.text('bot'));
s.poke('el', 90); run(2);
ok(s.text('bot') === 'z = ∞', 'the north pole is infinity', s.text('bot'));
s.poke('el', -90); run(2);
ok(s.text('bot').startsWith('z = 0   f(z) = -1'), 'the south pole is the centre of the view', s.text('bot'));
s.mouse.x = 200; s.mouse.y = 100; run(2);
ok(s.text('bot').startsWith('리만 구'), 'off the sphere: what it is', s.text('bot'));
// the south pole cell is black-free, the cells around z = 1 include the zero's colours
enter('z');
run(4);
const sk = s.peek('SK');
ok(new Set(sk.slice(0, 72)).size >= 60 && new Set(sk.slice(35 * 72)).size >= 60, 'z on the sphere: all the phases around both poles', new Set(sk.slice(0, 72)).size);
// t on a mesh: the coarse pass again and again
enter('z^3+e^(it)');
run(4); const tA = s.peek('s3T'); run(10);
ok(s.peek('s3T') > tA && s.peek('s3Have') === 1, 'while t runs a fast machine redraws the fine mesh', s.peek('s3T') - tA, s.peek('s3Have'));
s.poke('budget', 400); s.poke('bFail', 401); run(8);
ok(s.peek('s3Have') === 2 || s.peek('s3Have') === 0, 'and a slow one the coarse mesh', s.peek('s3Have'));
s.poke('budget', 30000);
press(32); run(4);
ok(s.peek('s3Have') === 1, 'stopped: the fine mesh');
press(32);
press(86); run(3);
ok(s.peek('view3') === 0 && fills() === 0, 'V a third time: the plane again');
press(32); s.settle();
ok(s.peek('rState') === 0 && s.peek('rLevel') === s.peek('maxLevel'), 'and the flat picture is drawn again');
press(71); run(3); press(86); run(4);
ok(s.peek('gridOn') === 0 && s.peek('view3') === 1 && s.base.grid.pen.strokes.length === 0, 'the grid picture and a mesh are not shown together');
press(86); press(86);
press(82);
// ---- v2.1: the pointer alone - the row of buttons, the formula pad
const tap = (x, y) => { s.mouse.x = x; s.mouse.y = y; run(1); s.mouse.down = true; run(2); s.mouse.down = false; run(2); };
const btn = (k) => tap(34 * k - 257, -124);                                  // button k of the row
const KEYS = ['7', '8', '9', '(', ')', 'z', 'i', 'e', 'pi', '^', 'BS', 'AC', '4', '5', '6', '*', '/', 'x', 'y', 'a', 't', 'c', ',', '^2', '1', '2', '3', '+', '-', 'sin', 'cos', 'tan', 'exp', 'ln', 'sqrt', 'abs', '0', '.', 're', 'im', 'arg', 'sinh', 'cosh', 'tanh', 'asin', 'acos', 'atan', 'gamma', 'zeta', 'iter', 'esc', 'asinh', 'acosh', 'atanh', 'sec', 'csc', 'cot', 'conj', 'NO', 'OK'];
const keyTap = (name) => { const k = KEYS.indexOf(name); if (k < 0) throw new Error('no key ' + name); tap(40 * (k % 12) - 220, -27 - 24 * Math.floor(k / 12)); };
const type = (...names) => names.forEach(keyTap);
const clones = s.entities.filter(e => e.obj === 'btn' && e.clone);
ok(clones.length === 75 && clones[0].text.trim() === '식' && clones[14].text.trim() === '7' && clones[74].text.trim() === '≡', 'the buttons are there', clones.length);
press(49); run(2);
ok(clones.slice(0, 14).every(c => c.visible) && clones.slice(14, 74).every(c => !c.visible) && clones[74].visible, 'the row is shown, the pad is not');
ok(clones[0].pen.x === -223 && clones[0].pen.y === -124 && clones[14].pen.x === -220 && clones[14].pen.y === -27 && clones[73].pen.x === 220 && clones[73].pen.y === -123, 'each at its place');
btn(3);
ok(s.peek('exAt') === 2 && s.text('top') === 'f(z) = z', 'the next-example button', s.text('top'));
btn(2);
ok(s.peek('exAt') === 1, 'the one before');
const vg = s.peek('vcx');
btn(4);
ok(s.peek('vupp') === 0.015625 / 2 && s.peek('vcx') === vg && s.peek('MKX').length === 0, 'the + button zooms about the middle, and the press is not a click on the picture', s.peek('vupp'));
btn(5); btn(5);
ok(s.peek('vupp') === 0.015625 * 2, 'the - button');
s.poke('vcx', 1); btn(6);
ok(s.peek('vcx') === 0 && s.peek('vupp') === 0.015625, 'the home button');
const cm = s.peek('cmode'); btn(7); ok(s.peek('cmode') === (cm + 1) % 4, 'the colour button'); btn(7); btn(7); btn(7);
btn(8); ok(s.peek('axesOn') === 0 && clones[7].colour !== '#ffd84a', 'the axes button'); btn(8); run(2);
ok(s.peek('axesOn') === 1 && clones[7].colour === '#ffd84a', 'a button that is on is lit', clones[7].colour);
btn(9); ok(s.peek('gridOn') === 1, 'the grid button'); btn(9);
btn(10); ok(s.peek('view3') === 1, 'the view button'); btn(10); btn(10); ok(s.peek('view3') === 0, 'three times round');
btn(11); ok(s.peek('hiq') === 1, 'the finer button'); btn(11);
btn(14); run(2);
ok(s.peek('helpOn') === 1 && s.base.help.visible && clones.slice(0, 14).every(c => !c.visible), 'the ? button shows the help, the row goes');
tap(0, 0);
ok(s.peek('helpOn') === 0 && s.peek('MKX').length === 0 && clones[0].visible, 'a press anywhere closes it (and is not a click on the picture)');
tap(224, 125); run(2);
ok(s.peek('menuOn') === 0 && clones.slice(0, 14).every(c => !c.visible) && clones[74].visible, 'the corner button hides the row');
tap(-223, -124);
ok(s.peek('padOn') === 0, 'a hidden button does nothing');
tap(224, 125); run(2);
ok(s.peek('menuOn') === 1 && clones[0].visible, 'and shows it again');
// the pad
btn(1); run(2);
ok(s.peek('padOn') === 1 && s.base.pad.visible && s.base.padl.visible && clones.slice(14, 74).every(c => c.visible) && clones.slice(0, 14).every(c => !c.visible), 'the formula button opens the pad');
ok(s.text('padl') === 'f(z) = (z^2-1)(z-2-i)^2/(z^2+2+2i)_', 'it starts with the formula as it is', s.text('padl'));
keyTap('AC'); run(1);
ok(s.text('padl') === 'f(z) = _', 'AC empties it', s.text('padl'));
type('(', 'z', '^2', '-', '1', ')', '/', 'sin', 'pi', 'z', ')'); run(1);
ok(s.text('padl') === 'f(z) = (z^2-1)/sin(piz)_', 'keys write', s.text('padl'));
keyTap('BS'); keyTap('BS'); type('*', 'z', ')'); run(1);
ok(s.text('padl') === 'f(z) = (z^2-1)/sin(pi*z)_', 'the back key takes one away', s.text('padl'));
const mk0 = s.peek('MKX').length;
tap(0, 60);
ok(s.peek('padOn') === 1 && s.peek('MKX').length === mk0 && s.peek('vcx') === 0, 'a press above the pad does nothing');
keyTap('OK'); run(2);
ok(s.peek('padOn') === 0 && s.text('top') === 'f(z) = (z^2-1)/sin(pi*z)' && !s.base.pad.visible && clones[0].visible, 'OK takes the formula', s.text('top'));
tap(-200, 127); run(2);
ok(s.peek('padOn') === 1, 'the formula in the corner opens the pad too');
type('AC', 'z', '+', '*', 'OK'); run(1);
ok(s.peek('padOn') === 1 && s.text('padl').startsWith('식이 맞지 않습니다'), 'a wrong formula keeps the pad open and says so', s.text('padl'));
keyTap('BS'); run(1);
ok(s.text('padl') === 'f(z) = z+_', 'the next key shows the text again', s.text('padl'));
keyTap('NO'); run(2);
ok(s.peek('padOn') === 0 && s.text('top') === 'f(z) = (z^2-1)/sin(pi*z)', 'cancel leaves the formula as it was', s.text('top'));
btn(1); type('AC', 'OK'); run(1);
ok(s.peek('padOn') === 1, 'OK on an empty line does nothing');
type('esc', 'z', '^2', '+', 'c', ',', '3', '0', ')', 'OK'); run(2);
ok(s.text('top') === 'f(z) = esc(z^2+c,30)', 'a formula with a comma', s.text('top'));
btn(1); type('AC', '(', '1', '+', '2', 'i', ')', '^', '(', '3', '-', 'i', ')', 'OK'); run(2);
ok(s.text('top') === '(1+2i)^(3-i) = -27.43638199 + 19.78931037i', 'the calculator by the pad', s.text('top'));
// a by the pointer, t by its button
btn(1); type('AC', 'z', '^2', '+', 'a', 'OK'); run(2);
btn(13); run(2);
ok(s.peek('aMode') === 1 && clones[12].colour === '#ffd84a', 'the a button');
tap(64, 32);
ok(s.peek('aRe') === 1 && s.peek('aIm') === 0.5 && s.peek('vcx') === 0 && s.peek('MKX').length === 0, 'with it on a press puts a there', s.peek('aRe'), s.peek('aIm'));
s.mouse.x = 0; s.mouse.y = 0; run(1); s.mouse.down = true; run(1); s.mouse.x = -64; s.mouse.y = -64; run(2); s.mouse.down = false; run(2);
ok(s.peek('aRe') === -1 && s.peek('aIm') === -1 && s.peek('vcx') === 0, 'and dragging drags a, not the view');
btn(13);
tap(64, 32);
ok(s.peek('aRe') === -1 && s.peek('aMode') === 0, 'off again: a press is a click on the picture');
s.poke('playing', 1);
btn(1); type('AC', 'z', '+', 't', 'OK'); run(3);
const tb = s.peek('tPar'); run(20);
ok(s.peek('tPar') > tb && clones[11].colour === '#ffd84a', 't runs, its button is lit');
btn(12); const tc = s.peek('tPar'); run(20);
ok(s.peek('tPar') === tc && clones[11].colour === '#ffffff', 'the t button stops it');
btn(12);
// dragging the picture still moves it, a click still finds a zero
press(49); btn(3); btn(3);
ok(s.text('top') === 'f(z) = z^3-1', 'example 3 by the button', s.text('top'));
tap(67, 3);
ok(s.text('top') === '영점 z = 1', 'a click on the picture', s.text('top'));
s.mouse.x = 0; s.mouse.y = 0; run(1); s.mouse.down = true; run(1); s.mouse.x = 32; run(2); s.mouse.down = false; run(2);
ok(s.peek('vcx') === -0.5, 'a drag on the picture');
// a drag that starts on a button does not move the picture
s.mouse.x = -223; s.mouse.y = -124; run(1); s.mouse.down = true; run(1); s.mouse.y = 0; run(2); s.mouse.down = false; run(2);
ok(s.peek('vcx') === -0.5 && s.peek('vcy') === 0 && s.peek('padOn') === 1, 'a press on a button is not a drag');
keyTap('NO');
press(82);
// numbers
const fmt = (v) => { s.fn.fmt(v); return s.peek('fs'); };
const FM = [[0, '0'], [0.1 + 0.2, '0.3'], [12345.678, '12346'], [-3.14159265, '-3.1416'], [1e-7, '1e-7'], [123456789, '1.2346e8'], [0.001234567, '0.0012346'], [0.00012345, '1.2345e-4'], [999999.5, '1000000'], [-1e300, '-1e300'], [Infinity, '∞'], [-Infinity, '-∞'], [1, '1'], [100, '100'], [99999.4, '99999'], [2.5e-310, '2.5e-310']];
for (const [v, want] of FM) ok(fmt(v) === want, 'fmt ' + v, fmt(v), 'want', want);
console.log(bad ? `FAIL ${bad}` : 'PASS', 'max clones during the long drag', maxAlive);
process.exit(bad ? 1 : 0);
